=== ViniciusFCoracin/ProjetoMC322/src/XML/course.dtd
<!ELEMENT courses (course+)>
<!ELEMENT course (courseName,courseId,semesters)>
<!ELEMENT courseName (#PCDATA)>
<!ELEMENT courseId (#PCDATA)>
<!ELEMENT semesters (semester+)>
<!ELEMENT semester (disciplineId*)>
<!ELEMENT disciplineId (#PCDATA)>
<!ATTLIST semester period CDATA #REQUIRED>

=== ViniciusFCoracin/ProjetoMC322/src/XML/courses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE courses SYSTEM "course.dtd">
<courses>
    <course>
        <courseName> Ciência da Computação </courseName>
        <courseId> 42 </courseId>
        <semesters>
            <semester period="1">
                <disciplineId> MA111 </disciplineId>
                <disciplineId> MA141 </disciplineId>
                <disciplineId> F 128 </disciplineId>
                <disciplineId> MC102 </disciplineId>
            </semester>
            <semester period="2">
                <disciplineId> MA211 </disciplineId>
                <disciplineId> MA327 </disciplineId>
                <disciplineId> F 129 </disciplineId>
                <disciplineId> MC202 </disciplineId>
                <disciplineId> MC009 </disciplineId>
            </semester>
            <semester period="3">
                <disciplineId> MA311 </disciplineId>
                <disciplineId> MC358 </disciplineId>
                <disciplineId> MC322 </disciplineId>
                <disciplineId> ME323 </disciplineId>
            </semester>
        </semesters>
    </course>
    <course>
        <courseName> Engenharia da Computação </courseName>
        <courseId> 34 </courseId>
        <semesters>
            <semester period="1">
                <disciplineId> MA111 </disciplineId>
                <disciplineId> MA141 </disciplineId>
                <disciplineId> F 128 </disciplineId>
                <disciplineId> MC102 </disciplineId>
                <disciplineId> F 159 </disciplineId>
                <disciplineId> HZ291 </disciplineId>
                <disciplineId> QG101 </disciplineId>
            </semester>
            <semester period="2">
                <disciplineId> MA211 </disciplineId>
                <disciplineId> MA327 </disciplineId>
                <disciplineId> F 228 </disciplineId>
                <disciplineId> MC202 </disciplineId>
                <disciplineId> F 259 </disciplineId>
                <disciplineId> LA122 </disciplineId>
            </semester>
            <semester period="3">
                <disciplineId> EA513 </disciplineId>
                <disciplineId> F315 </disciplineId>
                <disciplineId> F 328 </disciplineId>
                <disciplineId> MC322 </disciplineId>
                <disciplineId> F 359 </disciplineId>
                <disciplineId> MA311 </disciplineId>
            </semester>
        </semesters>
    </course>
</courses>
